<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DouAccount extends Model
{
    protected $fillable = [
        'phone',
        'user_id',
        'share_url',
        'avatar_url',
        'nick',
        'username',
        'adzone_id'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::saved(function (self $douAccount) {
            //根据推广位绑定账号
            if ($douAccount->adzone_id) {
                session()->flash('alert', [
                    'type' => 'warning',
                    'content' => '成功绑定' . TbkOrder::bindAccountByAdzoneId($douAccount) . '个订单'
                ]);
            }
        });
    }

    public function tbkorders()
    {
        return $this->hasMany(TbkOrder::class);
    }

    public function doutoptasks()
    {
        return $this->hasMany(DouTopTask::class, 'aweme_author_id', 'user_id');
    }
}
