<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;

class TbkAuthorize extends Model
{
    protected $fillable = ['active', 'auth_json'];

    protected $casts = [
        'active' => 'boolean',
        'auth_json' => 'json'
    ];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        //提取失效时间
        static::saving(function (TbkAuthorize $authorize) {
            $auth_arr = $authorize->auth_json;
            $authorize->expire_time = date('Y-m-d H:i:s', Arr::get($auth_arr, 'expire_time') / 1000);
            $authorize->tb_user_nick = Arr::get($auth_arr, 'taobao_user_nick');
            $authorize->tb_user_id = Arr::get($auth_arr, 'taobao_user_id');
            $authorize->access_token = Arr::get($auth_arr, 'access_token');
        });
    }

    public function tbkOrders()
    {
        return $this->hasMany(TbkOrder::class, 'authorize_id');
    }
}
